### ISSUE TITLE
MQ Staging and Prod needs specific Helm values

### ISSUE THREAD

**Issue by rikgig** [cloud-native-toolkit/multi-tenancy-gitops-apps#6]
Executing the tutorial for MQ with GitOps, I've found that the actual process is connecting the Spring app from the staging environment to the MQ initially created in the dev environment.

This is caused by the pipeline execution that actually creates the values.yaml file in the multi-tenancy-gitops-apps/mq/environments/staging/mq-spring-app/ as an empty values file and only the one from the packaged chart is used. This one points to the dev environment.

So when dynamically creating this file, a values file specific to the environment must be used. One that will have the following content:

```
global: {}
mq-spring-app:
  configmap:
    CONNECTION_NAME: qm-dev-ibm-mq.staging.svc.cluster.local(1414) 
```

Notice that the namespace in the service connection is "staging", replacing the original "dev" value.

The exact same approach is needed when doing the promotion from staging -> prod
